using System;
using AddressBookSystem;
Contact addressBook = new Contact();
Console.WriteLine("Enter the First Name: ");
addressBook.FirstName = Console.ReadLine();
Console.WriteLine("Enter the Last Name: ");
addressBook.LastName = Console.ReadLine();
Console.WriteLine("Enter the Address: ");
addressBook.Address = Console.ReadLine();
Console.WriteLine("Enter the City: ");
addressBook.City = Console.ReadLine();
Console.WriteLine("Enter the State: ");
addressBook.State = Console.ReadLine();
Console.WriteLine("Enter the Zip Code: ");
addressBook.ZipCode = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the Phone Number: ");
addressBook.PhoneNumber = Convert.ToInt64(Console.ReadLine());
Console.WriteLine("Enter the EmailId: ");
addressBook.EmailId = Console.ReadLine();
Console.WriteLine("The Contact details are: " + addressBook.FirstName + " " + addressBook.LastName + " " + addressBook.Address + " " + addressBook.City + " " + addressBook.State + " " + addressBook.ZipCode+" "+addressBook.PhoneNumber+" "+addressBook.EmailId);